# Generated by Django 6.0.3 on 2026-03-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_remove_plantreading_plant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantreading',
            name='condition',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('neutral', 'Neutral'), ('bad', 'Bad')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plantreading',
            name='plant_messages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
