# Generated by Django 5.2.14 on 2026-05-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readings", "0003_plantreading_condition_plantreading_plant_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantreading",
            name="device_id",
            field=models.CharField(default="default_device", max_length=100),
        ),
        migrations.AddField(
            model_name="plantreading",
            name="humidity_levels",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="plantreading",
            name="temperature_levels",
            field=models.FloatField(default=0.0),
        ),
    ]
