# Generated by Django 5.2.14 on 2026-05-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "readings",
            "0004_plantreading_device_id_plantreading_humidity_levels_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AppMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(default="sfw", max_length=10)),
            ],
        ),
    ]
